name: Build Plugin

on:
  push:
    branches:
      - main  # Adjust if you use a different default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Download Spigot API for compilation
      - name: Download Spigot API
        run: |
          mkdir libs
          curl -L -o libs/spigot-api.jar https://repo.spigotmc.org/repository/spigot-public/org/spigotmc/spigot-api/1.20.4-R0.1-SNAPSHOT/spigot-api-1.20.4-R0.1-SNAPSHOT.jar

      # Step 4: Compile plugin
      - name: Compile plugin
        run: |
          mkdir -p build
          javac -cp libs/spigot-api.jar -d build $(find src -name "*.java")
          cp resources/plugin.yml build/
          cd build && jar cf DualProfilePlugin.jar *

      # Step 5: Upload the compiled JAR file as an artifact
      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v2
        with:
          name: DualProfilePlugin
          path: build/DualProfilePlugin.jar
